### ISSUE TITLE
Bug: when used with ssr and clicking into html area

### ISSUE THREAD

**Issue by frank-dspeed** [canjs/can-dom-events#41]
The problem is when i click on a part of the page that has no element so it is inside <html>
then:
```
-make-delegate-event-tree.js:28 Uncaught TypeError: cur.matches is not a function
    at Object.eval (http://master.peep:3030/node_modules/can-dom-events/helpers/-make-delegate-event-tree.js:28:15)
    at String.eval (http://master.peep:3030/node_modules/can-reflect/reflections/shape/shape.js:445:21)
    at Object.eachListLike (http://master.peep:3030/node_modules/can-reflect/reflections/shape/shape.js:376:17)
    at Object.eachIndex (http://master.peep:3030/node_modules/can-reflect/reflections/shape/shape.js:338:16)
    at Object.eachKey (http://master.peep:3030/node_modules/can-reflect/reflections/shape/shape.js:443:16)
    at Object.each (http://master.peep:3030/node_modules/can-reflect/reflections/shape/shape.js:309:16)
    at HTMLHtmlElement.handler.delegated.(anonymous function) (http://master.peep:3030/node_modules/can-dom-events/helpers/-make-delegate-event-tree.js:24:16)
```

cur === html of the whole side as used via ssr

```
 "object" ["canMon Jan 29 2018 20:18:04 GMT+0000 (WET)"]0: "canMon Jan 29 2018 20:18:04 GMT+0000 (WET)"length: 1__proto__: Array(0)concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toString: ƒ toString()unshift: ƒ unshift()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}__proto__: Object

```

**Comment by justinbmeyer** [comment]
Thanks, we were able to see this ourselves.  Will fix soon.
